/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import datos.DALCategoria;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
import utiles.GestorSistema;

/**
 *
 * @author Toledo
 */
public class FrmCategoria extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCategoria.class.getName());
    private GestorSistema gestor;
    public FrmCategoria() {
        initComponents();
        gestor = GestorSistema.getInstancia();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        txtCategorias = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        jLabel2.setText("Categorías");

        btnGuardar.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnModificar.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnVolver.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnVolver))
                .addGap(21, 21, 21))
        );

        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoriasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCategorias);

        txtCategorias.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        txtCategorias.addActionListener(this::txtCategoriasActionPerformed);

        jLabel3.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel3.setText("Categoría:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void llenarTabla() {
        try {
            ArrayList<Categoria> lista = DALCategoria.listarCategorias();
            DefaultTableModel modelo = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Hacer la tabla no editable
                }
            };
            
            modelo.addColumn("ID");
            modelo.addColumn("Categoría");
            
            for (Categoria cat : lista) {
                Object fila[] = {cat.getIdCategoria(), cat.getNombre()};
                modelo.addRow(fila);
            }
            
            tblCategorias.setModel(modelo);
            
            // Ajustar ancho de columnas
            if (tblCategorias.getColumnModel().getColumnCount() > 0) {
                tblCategorias.getColumnModel().getColumn(0).setPreferredWidth(50);  // ID
                tblCategorias.getColumnModel().getColumn(1).setPreferredWidth(300); // Categoría
            }
            
            logger.info("Tabla de categorías cargada con " + lista.size() + " registros");
            
        } catch (Exception ex) {
            logger.severe("Error al llenar tabla de categorías: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, 
                "Error al cargar las categorías: " + ex.getMessage(),
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void limpiar() {
        txtId.setText("");
        txtCategorias.setText("");
        txtCategorias.requestFocus();
        
        // Deseleccionar fila de la tabla
        tblCategorias.clearSelection();
    }
    
    private boolean validarCampos() {
        categoria = txtCategorias.getText().trim();
        
        if (categoria.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Ingrese el nombre de la categoría", 
                "AVISO", 
                JOptionPane.WARNING_MESSAGE);
            txtCategorias.requestFocus();
            return false;
        }
        
        if (categoria.length() < 2) {
            JOptionPane.showMessageDialog(this, 
                "El nombre de la categoría debe tener al menos 2 caracteres", 
                "AVISO", 
                JOptionPane.WARNING_MESSAGE);
            txtCategorias.requestFocus();
            return false;
        }
        
        return true;
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!validarCampos()) {
            return;
        }
        
        try {
            if (DALCategoria.insertarCategoria(categoria)) {
                JOptionPane.showMessageDialog(this, 
                    "Categoría agregada correctamente", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
                logger.info("Categoría registrada: " + categoria);
                llenarTabla();
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "No se pudo agregar la categoría (puede que ya exista)", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            logger.severe("Error al registrar categoría: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, 
                "Error al registrar categoría: " + ex.getMessage(),
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Seleccione una categoría de la tabla para modificar", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!validarCampos()) {
            return;
        }
        
        try {
            idCategoria = Integer.parseInt(txtId.getText());
            
            if (DALCategoria.modificarCategoria(idCategoria, categoria)) {
                JOptionPane.showMessageDialog(this, 
                    "Categoría modificada correctamente", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
                logger.info("Categoría modificada - ID: " + idCategoria + " - Nombre: " + categoria);
                llenarTabla();
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "No se pudo modificar la categoría", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, 
                "ID de categoría inválido", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            logger.severe("Error al modificar categoría: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, 
                "Error al modificar categoría: " + ex.getMessage(),
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Seleccione una categoría de la tabla para eliminar", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de eliminar esta categoría?\n\n" +
            "ADVERTENCIA: Si hay productos asociados a esta categoría,\n" +
            "no podrá ser eliminada hasta que se cambien o eliminen esos productos.", 
            "Confirmar Eliminación", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                idCategoria = Integer.parseInt(txtId.getText());
                
                if (DALCategoria.eliminarCategoria(idCategoria)) {
                    JOptionPane.showMessageDialog(this, 
                        "Categoría eliminada correctamente", 
                        "Éxito", 
                        JOptionPane.INFORMATION_MESSAGE);
                    logger.info("Categoría eliminada - ID: " + idCategoria);
                    llenarTabla();
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(this, 
                        "No se pudo eliminar la categoría (puede tener productos asociados)", 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, 
                    "ID de categoría inválido", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                logger.severe("Error al eliminar categoría: " + ex.getMessage());
                JOptionPane.showMessageDialog(this, 
                    "Error al eliminar categoría: " + ex.getMessage(),
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriasMouseClicked
        int fila = tblCategorias.getSelectedRow();
        
        if (fila >= 0) {
            try {
                txtId.setText(tblCategorias.getValueAt(fila, 0).toString());
                txtCategorias.setText(tblCategorias.getValueAt(fila, 1).toString());
                
                logger.fine("Categoría seleccionada - ID: " + txtId.getText());
            } catch (Exception ex) {
                logger.warning("Error al cargar datos de la categoría seleccionada: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_tblCategoriasMouseClicked

    private void txtCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriasActionPerformed
        if (!txtCategorias.getText().trim().isEmpty()) {
            btnGuardarActionPerformed(evt);
        }
    }//GEN-LAST:event_txtCategoriasActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        gestor.getHistorialNavegacion().navegarA("Principal");
        logger.info("Volviendo al formulario principal");
        
        // Simplemente cerrar este formulario
        // NO abrir un nuevo FrmPrincipal
        this.dispose();
        
        // Si realmente necesitas asegurarte de que el principal esté visible,
        // puedes usar esta lógica:
        java.awt.EventQueue.invokeLater(() -> {
            for (Window window : Window.getWindows()) {
                if (window instanceof FrmPrincipal) {
                    window.setVisible(true);
                    window.toFront();
                    break;
                }
            }
        });
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCategorias;
    private javax.swing.JTextField txtCategorias;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
    private String categoria;
    private int idCategoria;
}
